apiVersion: v1
kind: Service
metadata:
  name: promptionary-backend
  labels:
    app: promptionary
    component: backend
spec:
  type: LoadBalancer
  selector:
    app: promptionary
    component: backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: promptionary-backend-internal
  labels:
    app: promptionary
    component: backend
spec:
  type: ClusterIP
  selector:
    app: promptionary
    component: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http