apiVersion: apps/v1
kind: Deployment
metadata:
  name: promptionary-frontend
  labels:
    app: promptionary
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: promptionary
      component: frontend
  template:
    metadata:
      labels:
        app: promptionary
        component: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/promptionary-frontend:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: VITE_API_URL
          value: "http://promptionary-backend-internal:3000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5