name: Deploy Frontend to GKE

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: promptionary-gke
      GKE_ZONE: us-central1
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/promptionary-frontend:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account-key.json
          gcloud auth activate-service-account --key-file=/tmp/service-account-key.json

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t $IMAGE -f apps/frontend/Dockerfile .

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      - name: Deploy to GKE
        run: |
          # Create ConfigMap for environment variables using internal service name
          kubectl create configmap promptionary-frontend-config \
            --from-literal=VITE_API_URL="http://promptionary-backend-service:3000" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Create or update deployment
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: promptionary-frontend
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: promptionary-frontend
            template:
              metadata:
                labels:
                  app: promptionary-frontend
              spec:
                containers:
                - name: promptionary-frontend
                  image: $IMAGE
                  ports:
                  - containerPort: 80
                  envFrom:
                  - configMapRef:
                      name: promptionary-frontend-config
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "256Mi"
                      cpu: "200m"
          EOF
          
          # Create service for internal communication
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Service
          metadata:
            name: promptionary-frontend-service
          spec:
            selector:
              app: promptionary-frontend
            ports:
            - protocol: TCP
              port: 80
              targetPort: 80
            type: ClusterIP
          EOF
          
          # Create external LoadBalancer service
          kubectl expose deployment promptionary-frontend --type=LoadBalancer --port=80 --target-port=80 --name=promptionary-frontend-external || true 