name: Deploy to Test Environment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: promptionary-gke-test
      GKE_ZONE: us-central1-a
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/promptionary-backend:test-${{ github.run_id }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account-key.json
          gcloud auth activate-service-account --key-file=/tmp/service-account-key.json

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          mkdir -p $HOME/.kube
          touch $HOME/.kube/config
          echo "use-gcp-auth-plugin: true" >> $HOME/.kube/config

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      - name: Create Cloud SQL Credentials Secret
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account-key.json
          kubectl create secret generic cloudsql-instance-credentials \
            --from-file=key.json=/tmp/service-account-key.json \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Build Docker image
        run: |
          docker build -t $IMAGE -f apps/backend/Dockerfile .

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy Backend to Test
        run: |
          # Create ConfigMap for environment variables
          kubectl create configmap promptionary-backend-config \
            --from-literal=DATABASE_URL="postgresql://${{ secrets.TEST_DB_USER }}:${{ secrets.TEST_DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.TEST_DB_NAME }}" \
            --from-literal=OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --from-literal=ENVIRONMENT="test" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Create Secret for Cloud SQL credentials
          kubectl create secret generic promptionary-db-secret \
            --from-literal=username="${{ secrets.TEST_DB_USER }}" \
            --from-literal=password="${{ secrets.TEST_DB_PASSWORD }}" \
            --from-literal=database="${{ secrets.TEST_DB_NAME }}" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Deploy with Cloud SQL Auth Proxy
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: promptionary-backend
            labels:
              environment: test
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: promptionary-backend
            template:
              metadata:
                labels:
                  app: promptionary-backend
                  environment: test
              spec:
                containers:
                - name: promptionary-backend
                  image: $IMAGE
                  ports:
                  - containerPort: 3000
                  envFrom:
                  - configMapRef:
                      name: promptionary-backend-config
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "256Mi"
                      cpu: "200m"
                - name: cloud-sql-proxy
                  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
                  command:
                  - "/cloud-sql-proxy"
                  - "${{ secrets.TEST_DB_INSTANCE_CONNECTION_NAME }}"
                  - "--credentials-file=/secrets/cloudsql/key.json"
                  securityContext:
                    runAsNonRoot: true
                  volumeMounts:
                  - name: cloudsql-instance-credentials
                    mountPath: /secrets/cloudsql
                    readOnly: true
                volumes:
                - name: cloudsql-instance-credentials
                  secret:
                    secretName: cloudsql-instance-credentials
          EOF
          
          # Create services
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Service
          metadata:
            name: promptionary-backend-service
          spec:
            selector:
              app: promptionary-backend
            ports:
            - protocol: TCP
              port: 3000
              targetPort: 3000
            type: NodePort
          EOF

      - name: Run Database Migrations
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/promptionary-backend
          kubectl exec deployment/promptionary-backend -- npx prisma migrate deploy

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: promptionary-gke-test
      GKE_ZONE: us-central1-a
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/promptionary-frontend:test-${{ github.run_id }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account-key.json
          gcloud auth activate-service-account --key-file=/tmp/service-account-key.json

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          mkdir -p $HOME/.kube
          touch $HOME/.kube/config
          echo "use-gcp-auth-plugin: true" >> $HOME/.kube/config

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      - name: Build Docker image
        run: |
          docker build -t $IMAGE -f apps/frontend/Dockerfile .

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy Frontend to Test
        run: |
          # Create ConfigMap for environment variables
          kubectl create configmap promptionary-frontend-config \
            --from-literal=NODE_ENV="production" \
            --from-literal=ENVIRONMENT="test" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Deploy frontend
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: promptionary-frontend
            labels:
              environment: test
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: promptionary-frontend
            template:
              metadata:
                labels:
                  app: promptionary-frontend
                  environment: test
              spec:
                containers:
                - name: promptionary-frontend
                  image: $IMAGE
                  ports:
                  - containerPort: 80
                  envFrom:
                  - configMapRef:
                      name: promptionary-frontend-config
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "50m"
                    limits:
                      memory: "128Mi"
                      cpu: "100m"
          EOF
          
          # Create services
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Service
          metadata:
            name: promptionary-frontend-service
          spec:
            selector:
              app: promptionary-frontend
            ports:
            - protocol: TCP
              port: 80
              targetPort: 80
            type: NodePort
          EOF
          
          # Deploy Ingress for test domain routing
          kubectl apply -f k8s/test-ingress.yaml

      - name: Get Service URLs
        run: |
          echo "Waiting for Ingress to be ready..."
          kubectl wait --for=condition=ready --timeout=300s ingress/promptionary-ingress || true
          
          echo "Test environment deployed!"
          echo "Test URL: https://test.promptionary.ai"
          echo ""
          echo "Note: SSL certificate provisioning may take up to 15 minutes."