name: Deploy Backend to GKE

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: promptionary-gke-prod
      GKE_ZONE: us-central1
      IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/promptionary-backend:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account-key.json
          gcloud auth activate-service-account --key-file=/tmp/service-account-key.json

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          mkdir -p $HOME/.kube
          touch $HOME/.kube/config
          echo "use-gcp-auth-plugin: true" >> $HOME/.kube/config

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

      - name: Create Cloud SQL Credentials Secret
        run: |
          # Extract the service account key and create the Cloud SQL credentials secret
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account-key.json
          kubectl create secret generic cloudsql-instance-credentials \
            --from-file=key.json=/tmp/service-account-key.json \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Build Docker image
        run: |
          docker build -t $IMAGE -f apps/backend/Dockerfile .

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy to GKE
        run: |
          # Create ConfigMap for environment variables
          kubectl create configmap promptionary-backend-config \
            --from-literal=DATABASE_URL="postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.DB_NAME }}" \
            --from-literal=OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Create Secret for Cloud SQL credentials
          kubectl create secret generic promptionary-db-secret \
            --from-literal=username="${{ secrets.DB_USER }}" \
            --from-literal=password="${{ secrets.DB_PASSWORD }}" \
            --from-literal=database="${{ secrets.DB_NAME }}" \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Create or update deployment with Cloud SQL Auth Proxy
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: promptionary-backend
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: promptionary-backend
            template:
              metadata:
                labels:
                  app: promptionary-backend
              spec:
                containers:
                - name: promptionary-backend
                  image: $IMAGE
                  ports:
                  - containerPort: 3000
                  envFrom:
                  - configMapRef:
                      name: promptionary-backend-config
                  resources:
                    requests:
                      memory: "128Mi"
                      cpu: "100m"
                    limits:
                      memory: "256Mi"
                      cpu: "200m"
                - name: cloud-sql-proxy
                  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
                  command:
                  - "/cloud-sql-proxy"
                  - "${{ secrets.DB_INSTANCE_CONNECTION_NAME }}"
                  - "--credentials-file=/secrets/cloudsql/key.json"
                  securityContext:
                    runAsNonRoot: true
                  volumeMounts:
                  - name: cloudsql-instance-credentials
                    mountPath: /secrets/cloudsql
                    readOnly: true
                volumes:
                - name: cloudsql-instance-credentials
                  secret:
                    secretName: cloudsql-instance-credentials
          EOF
          
          # Create service for internal communication
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Service
          metadata:
            name: promptionary-backend-service
          spec:
            selector:
              app: promptionary-backend
            ports:
            - protocol: TCP
              port: 3000
              targetPort: 3000
            type: NodePort
          EOF

      - name: Run Database Migrations
        run: |
          # Wait for deployment to be ready
          kubectl wait --for=condition=available --timeout=300s deployment/promptionary-backend
          
          # Run database migrations
          kubectl exec deployment/promptionary-backend -- npx prisma migrate deploy 